# Generated by Django 4.1.7 on 2023-04-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='in_person',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
