# Generated by Django 4.1.7 on 2023-04-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='numberOfRooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_chain',
            name='numberOfHotels',
            field=models.IntegerField(default=0),
        ),
    ]
