# Generated by Django 4.1.7 on 2023-03-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_hotels_hotel_rename_hotel_chains_hotel_chain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_chain',
            old_name='ChainRating',
            new_name='rating',
        ),
    ]
