# Generated by Django 4.1.7 on 2023-04-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservation_in_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='cash',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
