# Generated by Django 4.1.7 on 2023-04-01 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('capacity', models.CharField(choices=[], max_length=50)),
                ('extrabed', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('view', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
            options={
                'unique_together': {('room_number', 'hotel_id')},
            },
        ),
    ]
