# Generated by Django 4.1.7 on 2023-03-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_chainrating_hotel_chain_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hotel_chain',
            old_name='centAddress',
            new_name='address',
        ),
    ]
