# Generated by Django 4.1.7 on 2023-03-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_hoteladdress_hotel_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='chain_ID',
            new_name='chain_id',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_ID',
            new_name='hotel_id',
        ),
    ]
