# Generated by Django 4.1.7 on 2023-04-02 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_room_capacity_alter_room_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='nTelephones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None),
        ),
        migrations.AlterField(
            model_name='hotel_chain',
            name='nTelephones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None),
        ),
    ]
