# Generated by Django 4.1.7 on 2023-03-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_chain_id_hotel_chain_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_chain',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
