# Generated by Django 4.1.7 on 2023-04-02 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hotel_ntelephones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nTelephones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='hotel_chain',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hotel_chain',
            name='nTelephones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
    ]
