# Generated by Django 4.1.7 on 2023-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hotel_image_url_alter_hotel_chain_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='zone',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
    ]
