# Generated by Django 4.1.7 on 2023-04-02 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hotel_email_alter_hotel_ntelephones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='view',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
    ]
