# Generated by Django 4.1.7 on 2023-04-03 20:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_room_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('card_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('expiry_date', models.CharField(max_length=8)),
                ('cvv', models.CharField(max_length=4)),
                ('name_on_the_card', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('ssa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('card_info', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.card')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='view',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), null=True, size=None),
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_reservation', models.DateField(blank=True, default=datetime.datetime(2023, 4, 3, 16, 51, 7, 413205))),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('view', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), null=True, size=None)),
                ('extrabed', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.capacity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='payement_for',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payement')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservation')),
            ],
        ),
    ]
