# Generated by Django 4.1.7 on 2023-04-03 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_card_client_payement_alter_room_view_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 3, 16, 52, 17, 754714)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 16, 52, 17, 754714)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 16, 52, 17, 754714)),
        ),
    ]
