# Generated by Django 4.1.7 on 2023-04-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_reservation_date_of_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateField(),
        ),
    ]
