# Generated by Django 4.1.7 on 2023-04-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_reservation_date_of_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='card_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.card'),
        ),
        migrations.CreateModel(
            name='damage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
