# Generated by Django 4.1.7 on 2023-04-04 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_payement_card_info_damage_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='view',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
