# Generated by Django 4.1.7 on 2023-04-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_reservation_archive'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation_archive',
            table='reservation_archive',
        ),
    ]
