# Generated by Django 4.1.7 on 2023-04-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_reservation_archive_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation_archive',
            table='app_reservation_archive',
        ),
    ]
